// Muse Spark — interactive engine (zero deps)
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];

/* Theme */
const themeBtn = $('#themeBtn');
themeBtn.onclick = () => {
  const h = document.documentElement;
  h.dataset.theme = h.dataset.theme === 'dark' ? 'light' : 'dark';
};

/* Mobile */
$('#hamburger').onclick = () => $('#mobileMenu').classList.toggle('open');
$$('#mobileMenu a').forEach(a => a.onclick = () => $('#mobileMenu').classList.remove('open'));

/* Cursor glow */
addEventListener('pointermove', e => {
  const g = $('#cursorGlow');
  g.style.left = e.clientX + 'px'; g.style.top = e.clientY + 'px';
});

/* Particles */
(() => {
  const c = $('#particles'), x = c.getContext('2d');
  let W, H, pts = [];
  const resize = () => { W = c.width = innerWidth; H = c.height = innerHeight; };
  resize(); addEventListener('resize', resize);
  for (let i = 0; i < 90; i++) pts.push({ x: Math.random()*innerWidth, y: Math.random()*innerHeight, vx:(Math.random()-.5)*.4, vy:(Math.random()-.5)*.4, r:Math.random()*2+.4, h:Math.random()>.5?'124,92,255':'0,229,255' });
  (function loop(){
    x.clearRect(0,0,W,H);
    pts.forEach(p=>{ p.x+=p.vx; p.y+=p.vy; if(p.x<0||p.x>W)p.vx*=-1; if(p.y<0||p.y>H)p.vy*=-1;
      x.beginPath(); x.arc(p.x,p.y,p.r,0,7); x.fillStyle=`rgba(${p.h},.7)`; x.fill(); });
    // links
    for(let i=0;i<pts.length;i++) for(let j=i+1;j<pts.length;j++){
      const dx=pts[i].x-pts[j].x, dy=pts[i].y-pts[j].y, d=Math.hypot(dx,dy);
      if(d<130){ x.strokeStyle=`rgba(124,92,255,${(1-d/130)*.25})`; x.beginPath(); x.moveTo(pts[i].x,pts[i].y); x.lineTo(pts[j].x,pts[j].y); x.stroke(); }
    }
    requestAnimationFrame(loop);
  })();
})();

/* Typing hero */
(() => {
  const phrases = ['spark build my saas idea --verify','spark analyze sales.csv --insights','spark deploy --global --edge','spark rescue flaky-tests --prove-it'];
  let pi=0, ci=0, del=false; const el=$('#typed');
  (function tick(){
    const p=phrases[pi];
    el.textContent=p.slice(0,ci);
    if(!del){ ci++; if(ci>p.length+14) del=true; }
    else{ ci--; if(ci===0){ del=false; pi=(pi+1)%phrases.length; } }
    setTimeout(tick, del?28:62);
  })();
})();

/* Hero fake chat */
(() => {
  const box=$('#heroChat');
  const script=[['me','Can you ship a pricing page by today?'],['ai','On it. Scaffolding, styling, verifying… ✦'],['ai','Done — 98 Lighthouse, responsive, deployed. 🚀']];
  let i=0;
  function next(){
    box.innerHTML=''; i=0;
    const step=()=>{
      if(i>=script.length){ setTimeout(next,4200); return; }
      const [who,t]=script[i++];
      const d=document.createElement('div'); d.className='msg '+who; d.textContent=t; box.appendChild(d);
      setTimeout(step,1100);
    }; step();
  } next();
})();

/* Tilt */
(() => {
  const t=$('#tilt'); const hero=document.querySelector('.hero-visual');
  hero.addEventListener('pointermove',e=>{
    const r=hero.getBoundingClientRect();
    const rx=((e.clientY-r.top)/r.height-.5)*-14, ry=((e.clientX-r.left)/r.width-.5)*16;
    t.style.transform=`rotateX(${rx}deg) rotateY(${ry}deg)`;
  });
  hero.addEventListener('pointerleave',()=>t.style.transform='rotateX(0) rotateY(0)');
})();

/* Reveal + counters + nav shadow */
(() => {
  const io=new IntersectionObserver(es=>es.forEach(e=>{ if(e.isIntersecting){ e.target.classList.add('in'); io.unobserve(e.target);} }),{threshold:.12});
  $$('.reveal').forEach(el=>io.observe(el));
  const cio=new IntersectionObserver(es=>es.forEach(e=>{
    if(!e.isIntersecting) return; const el=e.target, end=+el.dataset.count; let s=0;
    const t=setInterval(()=>{ s+=Math.max(1,Math.round(end/40)); if(s>=end){s=end;clearInterval(t);} el.textContent=s+(end===99?'%':''); },40);
    cio.unobserve(el);
  }),{threshold:.6});
  $$('[data-count]').forEach(el=>cio.observe(el));
})();

/* Marquee duplicate */
($('#marqueeTrack').innerHTML += $('#marqueeTrack').innerHTML);

/* Tabs */
$$('.tab').forEach(b=>b.onclick=()=>{
  $$('.tab').forEach(x=>x.classList.remove('active')); b.classList.add('active');
  ['code','data','chat','terminal'].forEach(k=>$('#panel-'+k).classList.toggle('hidden',k!==b.dataset.tab));
});

/* Card spotlight */
$$('.cap').forEach(c=>c.addEventListener('pointermove',e=>{
  const r=c.getBoundingClientRect(); c.style.setProperty('--mx',(e.clientX-r.left)+'px'); c.style.setProperty('--my',(e.clientY-r.top)+'px');
}));

/* --- Code Forge --- */
const samples = {
  'pricing': lang => lang.includes('Python') ? `# pricing.py — generated by Spark\nplans = [{"name":"Starter","price":9},{"name":"Pro","price":29,"popular":True},{"name":"Scale","price":99}]\nfor p in plans:\n    star = " ★ POPULAR" if p.get("popular") else ""\n    print(f"{p['name']:10} ${p['price']}/mo{star}")`
  : lang==='React' ? `// Pricing.jsx — forged by Spark ⚡\nexport default function Pricing({plans}) {\n  return (\n    <section className="grid md:grid-cols-3 gap-6">\n      {plans.map(p => (\n        <div key={p.name} className={p.popular ? "glow ring-2 ring-cyan-400 scale-105" : "card"}>\n          {p.popular && <span className="badge">MOST POPULAR</span>}\n          <h3>{p.name}</h3><p className="price">\${p.price}<small>/mo</small></p>\n          <button>{p.cta ?? "Start free"}</button>\n        </div>))}\n    </section>\n  );\n}`
  : lang==='SQL' ? `-- pricing analytics — Spark\nSELECT plan,\n  COUNT(*) AS customers,\n  ROUND(AVG(mrr),2) AS avg_mrr,\n  SUM(CASE WHEN popular THEN 1 ELSE 0 END) AS popular_pick\nFROM subscriptions\nGROUP BY plan ORDER BY avg_mrr DESC;`
  : `<!-- pricing.html — forged by Spark ⚡ -->\n<section class="pricing">\n  <div class="tier"><h3>Starter</h3><p class="price">$9<small>/mo</small></p><button>Start free</button></div>\n  <div class="tier popular"><span>Most popular</span><h3>Pro</h3>\n    <p class="price">$29<small>/mo</small></p><button>Go Pro →</button></div>\n  <div class="tier"><h3>Scale</h3><p class="price">$99<small>/mo</small></p><button>Contact us</button></div>\n</section>\n<style>.popular{box-shadow:0 0 40px #00e5ff88;border:2px solid #00e5ff}</style>`,
  'login': lang => `// login — Spark secured ✦\nfunction validate({email,password}){\n  const errs=[];\n  if(!/^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$/.test(email)) errs.push("Enter a valid email");\n  if(password.length<8) errs.push("Min 8 characters");\n  if(!/[A-Z]/.test(password)) errs.push("Add an UPPERCASE letter");\n  return errs; // [] = ok → hash + session + MFA\n}`,
  'todo': lang => `// todo app — Spark minimal ⚡\nconst todos = new Map(); let id = 0;\nconst add = text => todos.set(++id, {id, text, done:false});\nconst toggle = id => todos.get(id).done ^= 1;\nconst list = (f='all') => [...todos.values()].filter(t => f==='all' || (f==='done')===t.done);\nadd("Ship with Spark ✦"); add("Verify with tests");`,
  'dashboard': lang => `// dashboard query — Spark\nSELECT date_trunc('day', created_at) AS day,\n  COUNT(*) AS signups,\n  SUM(mrr) AS revenue\nFROM events GROUP BY 1 ORDER BY 1; -- → feed to Data Pulse tab 📊`,
  'api': lang => `// rest api — Spark + FastAPI\nfrom fastapi import FastAPI\napp = FastAPI()\n@app.get("/health")\ndef health(): return {"status": "ok", "spark": "✦"}\n@app.post("/ideas")\ndef create_idea(idea: dict):\n    return {"id": 1, "plan": "verified", **idea}`
};
$('#forgeBtn').onclick = () => {
  const prompt = $('#codePrompt').value.toLowerCase();
  const lang = $('#codeLang').value;
  const key = Object.keys(samples).find(k => prompt.includes(k)) || 'pricing';
  $('#forgeFile').textContent = key + (lang==='React'?'.jsx':lang==='Python'?'.py':lang==='SQL'?'.sql':'.html');
  const out = $('#forgeOut'); const code = samples[key](lang);
  out.textContent=''; let i=0;
  const t=setInterval(()=>{ out.textContent=code.slice(0,i+=14); if(i>=code.length) clearInterval(t); },18);
};

/* --- Data Pulse --- */
let chartData = [];
function genData(mode){
  const n=28; chartData=[];
  for(let i=0;i<n;i++){
    let v;
    if(mode==='growth') v=20+i*2.6+Math.random()*14;
    else if(mode==='spike') v=22+Math.random()*10+(i>17&&i<23?70*Math.sin((i-17)/5*Math.PI):0);
    else v=50+Math.sin(i/3)*22+Math.random()*8;
    chartData.push(v);
  }
  const sum=chartData.reduce((a,b)=>a+b,0);
  $('#kpi1').textContent='$'+(sum/28*1.7/1000).toFixed(1)+'k';
  $('#kpi2').textContent=Math.round(sum*42).toLocaleString();
  $('#kpi3').textContent=(1+Math.random()*2).toFixed(1)+'%';
  $('#dataInsight').textContent = mode==='spike' ? 'Insight: viral spike detected days 18–22 — 3.1× baseline. Spark suggests: scale edge cache + trigger win-back flow.' : mode==='growth' ? 'Insight: steady compounding growth (+9.4% WoW). Spark suggests: raise Pro price test + ship referral loop.' : 'Insight: healthy weekly seasonality. Spark suggests: schedule deploys in troughs, promos at peaks.';
  drawChart();
}
function drawChart(){
  const c=$('#chart'), ctx=c.getContext('2d');
  const dpr=devicePixelRatio||1, w=c.clientWidth||600, h=220;
  c.width=w*dpr; c.height=h*dpr; ctx.scale(dpr,dpr);
  ctx.clearRect(0,0,w,h);
  const max=Math.max(...chartData)*1.15, min=Math.min(...chartData)*.85;
  const px=i=>20+i*(w-40)/(chartData.length-1), py=v=>h-24-((v-min)/(max-min))*(h-60);
  // grid
  ctx.strokeStyle='rgba(150,160,220,.15)'; for(let g=0;g<4;g++){const y=20+g*(h-60)/3; ctx.beginPath(); ctx.moveTo(20,y); ctx.lineTo(w-16,y); ctx.stroke();}
  const grad=ctx.createLinearGradient(0,0,w,0); grad.addColorStop(0,'#7c5cff'); grad.addColorStop(.5,'#00e5ff'); grad.addColorStop(1,'#ff4ecd');
  ctx.beginPath(); chartData.forEach((v,i)=>i?ctx.lineTo(px(i),py(v)):ctx.moveTo(px(i),py(v)));
  ctx.strokeStyle=grad; ctx.lineWidth=3; ctx.lineJoin='round'; ctx.stroke();
  ctx.lineTo(px(chartData.length-1),h-20); ctx.lineTo(px(0),h-20); ctx.closePath();
  const fg=ctx.createLinearGradient(0,0,0,h); fg.addColorStop(0,'rgba(0,229,255,.3)'); fg.addColorStop(1,'rgba(124,92,255,0)'); ctx.fillStyle=fg; ctx.fill();
  // dots
  ctx.fillStyle='#fff'; chartData.forEach((v,i)=>{ if(i%4===0){ctx.beginPath(); ctx.arc(px(i),py(v),3.4,0,7); ctx.fill();} });
}
$('#dataBtn').onclick=()=>genData($('#dataMode').value);
$('#dataMode').onchange=e=>genData(e.target.value);
genData('growth'); addEventListener('resize',drawChart);

/* --- Ask Spark chat --- */
const chatFull=$('#chatFull');
function addMsg(who,text){ const d=document.createElement('div'); d.className='msg '+who; d.textContent=text; chatFull.appendChild(d); chatFull.scrollTop=9999; }
function sparkReply(q){
  q=q.toLowerCase();
  if(q.includes('verif')||q.includes('test')) return 'I verify everything: I run the code, add tests, and show you logs + before/after. No “trust me” — only evidence. Try the Terminal tab → “spark test --coverage”.';
  if(q.includes('stack')||q.includes('build')) return 'My go-to: React + TypeScript frontend, Python/FastAPI or Node backend, Fabric/Postgres data, Azure + Docker deploy. But I adapt to YOUR repo in seconds.';
  if(q.includes('price')||q.includes('cost')) return 'This demo is free and runs fully client-side. For real projects, just describe the outcome — I’ll scope it into a tight plan first.';
  if(q.includes('who')||q.includes('you')) return 'I’m Muse Spark 1.3, running in opencode — an AI engineer that reasons, builds, runs, and verifies. Think pair-programmer with infinite stamina. ✦';
  if(q.includes('data')||q.includes('fabric')||q.includes('power bi')) return 'Love data. I do medallion lakehouses, DAX tuning, KQL real-time, and Power BI design. Check the Data Pulse tab for a live taste 📊';
  return 'Great question. In a real session I’d inspect your files, propose a 3-step plan, implement it, then run verification. Give me a repo + goal and watch me cook. ⚡';
}
addMsg('ai','Hey, I’m Spark ✦ — ask me how I build, verify, or ship. Or try “how do you verify code?”');
$('#chatSend').onclick=sendChat; $('#chatIn').addEventListener('keydown',e=>{if(e.key==='Enter')sendChat();});
function sendChat(){ const v=$('#chatIn').value.trim(); if(!v)return; addMsg('me',v); $('#chatIn').value=''; setTimeout(()=>addMsg('ai',sparkReply(v)),650); }

/* --- Terminal --- */
const outputs={
  'spark build --verify':['✓ scaffold … done','✓ types … 0 errors','✓ bundle … 84kb gzip','✓ a11y … AA pass','BUILD GREEN in 1.2s ✦'],
  'spark test --coverage':['▶ 48 tests …','✓ 47 passed · 1 flaky retried → pass','Coverage: 96.4% (lines) 91.2% (branches)','ALL GREEN — proof attached.'],
  'spark deploy --global':['→ edge: fra · sin · iad · gru','✓ health /health 200 in 38ms','✓ rollback snapshot saved','LIVE → https://spark-edge.app 🚀']
};
let termQueue=['spark build --verify'];
(function termLoop(){
  const el=$('#termTyped'); const cmd=termQueue[0]||'spark build --verify';
  let i=0; el.textContent='';
  const typing=setInterval(()=>{
    el.textContent=cmd.slice(0,++i);
    if(i>=cmd.length){ clearInterval(typing);
      setTimeout(()=>{
        const out=$('#termOut');
        out.innerHTML+=`<br><span class="t">$ ${cmd}</span><br>`+ (outputs[cmd]||['done ✦']).join('<br>');
        termQueue.push(termQueue.shift()); setTimeout(termLoop,1800);
      },500);
    }
  },55);
})();
$$('#panel-terminal [data-cmd]').forEach(b=>b.onclick=()=>{ termQueue=[b.dataset.cmd]; $('#termOut').innerHTML='<code>Terminal — Spark ops</code>'; });

/* Work filters */
$$('.filter').forEach(b=>b.onclick=()=>{
  $$('.filter').forEach(x=>x.classList.remove('active')); b.classList.add('active');
  $$('.work').forEach(w=>w.style.display=(b.dataset.f==='all'||w.dataset.cat===b.dataset.f)?'':'none');
});

/* Contact */
$('#contactForm').addEventListener('submit',e=>{
  e.preventDefault();
  const n=$('#cName').value;
  $('#contactOk').textContent=`Thanks ${n} ✦ — Spark received your brief and is already drafting the plan. (Demo form — no data sent.)`;
  e.target.reset();
});
